server:
  port: 9095
# actuator end point to check the state of the circuit breaker like health
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      callFirstService:
        register-health-indicator: true
        ring-buffer-size-in-closed-state: 6
        ring-buffer-size-in-half-open-state: 3
        wait-duration-in-open-state: 50s
        failure-rate-threshold: 50